### ISSUE TITLE
Demo  bi_axial_stress error

### ISSUE THREAD

**Issue by ramayzoraiz** [finsberg/pulse#12]
Hi, I tried running biaxial_stress_test demo on docker as well on anaconda and both times it gave error mentioned below.
**Problematic Jupyter Notebook Cell:**
```
# Create problem
problem = pulse.MechanicsProblem(geometry, material, bcs)
```
**Error:**
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-464b47056510> in <module>
      1 # Create problem
----> 2 problem = pulse.MechanicsProblem(geometry, material, bcs)

~/anaconda3/envs/pulse_plotly/lib/python3.9/site-packages/pulse/mechanicsproblem.py in __init__(self, geometry, material, bcs, bcs_parameters, solver_parameters)
    182 
    183         self._init_spaces()
--> 184         self._init_forms()
    185         self.solver_parameters = MechanicsProblem.defaul_solver_parameters()
    186         if solver_parameters is not None:

~/anaconda3/envs/pulse_plotly/lib/python3.9/site-packages/pulse/mechanicsproblem.py in _init_forms(self)
    226         )
    227 
--> 228         self._virtual_work += self._external_work(u, v)
    229 
    230         self._set_dirichlet_bc()

TypeError: unsupported operand type(s) for +=: 'Form' and 'Constant'
```

**Comment by finsberg** [comment]
Try to install the latest version of `pulse` 
```
python3 -m pip install fenics-pulse --upgrade
```
and let me know if this solves the issue or if the issue persists.

**Comment by ramayzoraiz** [comment]
Yes, it solved this. 
Currently docker/anaconda install fenics-pulse-2020.2.0 which cause this issue. pip installs fenics-pulse-2020.2.2 and issue is resolved.

**Comment by ramayzoraiz** [comment]
New issue has arisen and that is in last block cell of demo  biaxial_stress_test notebook.
```
Traceback (most recent call last):
  File "/home/zoraiz/anaconda3/envs/pulse_upgrade/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-22-7bc00516f84c>", line 2, in <module>
    get_ipython().run_line_magic('config', "InlineBademos/benchmark/problem1ckend.figure_format = 'retina'")

  File "/home/zoraiz/anaconda3/envs/pulse_upgrade/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2344, in run_line_magic
    result = fn(*args, **kwargs)

  File "/home/zoraiz/anaconda3/envs/pulse_upgrade/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)

  File "/home/zoraiz/anaconda3/envs/pulse_upgrade/lib/python3.9/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)

  File "/home/zoraiz/anaconda3/envs/pulse_upgrade/lib/python3.9/site-packages/IPython/core/magics/config.py", line 152, in config
    exec("cfg."+line, locals(), self.shell.user_ns)

  File "<string>", line 1
    cfg.InlineBademos/benchmark/problem1ckend.figure_format = 'retina'
    ^
SyntaxError: cannot assign to operator
```

**Comment by finsberg** [comment]
OK, I will make sure update the version on conda. Thanks for letting me know about this.

Try to remove the line saying
```
%config InlineBackend.figure_format = 'retina'
```
That should get rid of this error. Not really sure why you get this error.

**Comment by ramayzoraiz** [comment]
Yes, issue is solved. Thanks.
One more thing, I installed pulse from conda first and then updated it with pip. Demo run fine.
But when pulse is installed with pip from start. Then following error come in first line of this demo i.e. **from ufl.constantvalue import zero**
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-87a0cbe14b58> in <module>
----> 1 from ufl.constantvalue import zero
      2 from pulse.utils import mpi_comm_world
      3 import dolfin
      4 import matplotlib.pyplot as plt
      5 import numpy as np

ModuleNotFoundError: No module named 'ufl'
```

**Comment by finsberg** [comment]
If you install pulse without conda, then you need to install FEniCS separately. ufl is installed with FEniCS.

**Comment by ramayzoraiz** [comment]
Oh! Thanks for informing.
